### ISSUE TITLE
OSError: when running usage example

### ISSUE THREAD

**Issue by chingyuhelen** [emfomy/ckipnlp#12]
hi,
I was running the usage example [CKIPWS](https://ckipnlp.readthedocs.io/en/latest/src/readme.html#ckipws) and [CKIP-Parser](https://ckipnlp.readthedocs.io/en/latest/src/readme.html#id2),

but got the following error.
```
~/.local/lib/python3.6/site-packages/ckipnlp/parser/__init__.py in __init__(self, logger, inifile, wsinifile, **options)
     63         CkipParser(**options)
     64 
---> 65         self.__core.init_data(inifile)
     66 
     67         try:

src/parser/ckipparser.pyx in ckipnlp._core.parser.CkipParserCore.init_data()

OSError: 
```

I've already had my `LD_LIBRARY_PATH` set and was able to run `CKIPWS.py` and `CKIPCoreNLP3.py`.

Would you help me addressing the problems here?🤔

**Comment by emfomy** [comment]
Can you show me the code you run, the full log, the runtime environment?

**Comment by chingyuhelen** [comment]
Hi,

```console
$ echo $LD_LIBRARY_PATH
# /opt/ckip/CKIPWS_Linux/lib:/opt/ckip/CKIPParser_Linux/lib:

$ gcc --version
# gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
```

I tested it again. It turns out that I can only run in the ckip directory `CKIPParser_Linux` or `CKIPWS_Linux`.
Looks like the problem is that the file paths in the ini file are relative to the current working directory instead of `<ckipws-linux-root>` or `<ckipparser-linux-root>`.

**Comment by chingyuhelen** [comment]
Also, when I ran [CKIP-Parser](https://ckipnlp.readthedocs.io/en/latest/src/readme.html#id2) under the `CKIPParser_Linux` directory.

```python
import ckipnlp.parser
print(ckipnlp.__name__, ckipnlp.__version__)

# 1st part
ps = ckipnlp.parser.CkipParser(logger=False)
print(ps('中文字喔'))
for l in ps.apply_list(['中文字喔', '啊哈哈哈']): print(l)

# 2nd part
ps = ckipnlp.parser.CkipParser(logger=False)
print(ps('中文字喔'))
for l in ps.apply_list(['中文字喔', '啊哈哈哈']): print(l)
ps.apply_file(ifile='sample/sample.txt', ofile='output/sample.tree')
with open('output/sample.tree') as fin:
    print(fin.read())
```

I got the `1st part` running, but fail in the `2nd part`.
```
~/.local/lib/python3.6/site-packages/ckipnlp/parser/__init__.py in __init__(self, logger, inifile, wsinifile, **options)
     63         CkipParser(**options)
     64 
---> 65         self.__core.init_data(inifile)
     66 
     67         try:

src/parser/ckipparser.pyx in ckipnlp._core.parser.CkipParserCore.init_data()

OSError: 
```
It looks like I can't run `ps = ckipnlp.parser.CkipParser(logger=False)` multiple times.

**Comment by emfomy** [comment]
It is a know issue of CKIPWS and CKIPParser that multiple initialization is not possible since the C code initialize several things in global scope.

Does your code work correctly without multiple initialization?

**Comment by emfomy** [comment]
> I tested it again. It turns out that I can only run in the ckip directory `CKIPParser_Linux` or `CKIPWS_Linux`.
> Looks like the problem is that the file paths in the ini file are relative to the current working directory instead of `<ckipws-linux-root>` or `<ckipparser-linux-root>`.

The data files should be copied to the share directory of your python on pip install. Could you check if `<python-root>/share/ckipnlp` folder exists with `Data`, `Rule`, `RDB` within it?

**Comment by emfomy** [comment]
CKIPWS and CKIPParser moved to [CkipClassic](https://github.com/ckiplab/ckip-classic).
