### ISSUE TITLE
Co-Reference Pipeline sample code is not working

### ISSUE THREAD

**Issue by jungyitsai** [emfomy/ckipnlp#28]
I use sample code from document-reference, but I get the error-message `NodeIDAbsentError: Node 'None' is not in the tree`.
Do I misuse this sample code?

- document-reference
  - https://ckipnlp.readthedocs.io/en/latest/main/usage/pipeline.html#co-reference-pipeline

- my-colab-link
  -  https://colab.research.google.com/drive/11iHXf3K-SN9geg2t1X496ZzVT-UR3ONA?usp=sharing

- error-message
  - NodeIDAbsentError: Node 'None' is not in the tree

- sample code
```
from ckipnlp.pipeline import CkipCorefPipeline, CkipDocument

pipeline = CkipCorefPipeline()
doc = CkipDocument(raw='畢卡索他想，完蛋了')

# Co-Reference
corefdoc = pipeline(doc)
print(corefdoc.coref)
for line in corefdoc.coref:
    print(line.to_text())
```

**Comment by emfomy** [comment]
Sorry for my late response.
The Co-Reference pipeline depends on CkipClassic Parser Client backend.
To use the CkipClassic Parser Client backend, you need to

1. Register an account at http://parser.iis.sinica.edu.tw/v1/reg.exe
2. Set the environment variables `$CKIPPARSER_USERNAME` and `$CKIPPARSER_PASSWORD` to the username and password.

**Comment by emfomy** [comment]
CkipClassic updated.
https://github.com/ckiplab/ckip-classic/releases/tag/1.2.1

Now it will raise error if username/password is invalid.
