### ISSUE TITLE
What `%` means in Parsing Tree?

### ISSUE THREAD

**Issue by How-Wang** [emfomy/ckipnlp#30]
When using ***parsing tree*** and 
feeding a little bit longer sentence, I always get **`%`** at root, instead of `S`, `VP` or `NP`.
But I cannot find any information from document to know what it is.
**Is there anyone knows that?** 

![Coreference Resolution Example](https://user-images.githubusercontent.com/62500402/155284683-4775855d-763f-4ce2-ab69-a411d8f14d6a.jpg)

**Comment by emfomy** [comment]
It means that the library failed to recognize the parsing tree. It usually happens when the sentence is too long.

**Comment by How-Wang** [comment]
Thanks for your explanation!🤗
Hope CKIP CoreNLP Toolkit will be strong enough to deal with it in the future.
