### ISSUE TITLE
Link for CkipClassic Parser Client backend is not working

### ISSUE THREAD

**Issue by andyko0620** [emfomy/ckipnlp#32]
I want to use the CkipClassic Parser Client backend. However, the link [http://parser.iis.sinica.edu.tw/v1/reg.exe](http://parser.iis.sinica.edu.tw/v1/reg.exe) is not working so I can't register an account.

**Comment by ZenonLiao** [comment]
The service has been relaunched. Thank you for informing us.

**Comment by alalachin** [comment]
Is the link not working again? 
[account registration](http://parser.iis.sinica.edu.tw/v1/reg.exe)
