### ISSUE TITLE
Constituency Parsing in CkipPipeline is not working

### ISSUE THREAD

**Issue by andyko0620** [emfomy/ckipnlp#33]
I want to use Constituency Parsing in the CKIP package. The step I have done and the issue I encountered are as follows.
1. I registered an account at http://parser.iis.sinica.edu.tw/v1/reg.exe and got my username and password 
2. I followed the usage guideline in Pipelines ([https://ckipnlp.readthedocs.io/en/latest/main/usage/pipeline.html](https://ckipnlp.readthedocs.io/en/latest/main/usage/pipeline.html)).
3. The ws and pos in CkipPipeline are working properly. However, in Constituency Parsing stage, the program runs very slow and outputs an empty list ([[]]), which is not consistent with that of the online demo version.
Attached is the code, the output of the code, and the output of the online demo version for the same input. 
![0817_1](https://user-images.githubusercontent.com/71416023/185037321-c9e8483b-8160-47cb-bc26-446b74b001aa.png)
![0817_2](https://user-images.githubusercontent.com/71416023/185037341-163ba531-8b79-4cd7-a62b-ac588ff2fcd2.png)
![0817_3](https://user-images.githubusercontent.com/71416023/185037532-15f14772-d014-4367-9a30-e95cdc0da8b5.png)

**Comment by ZenonLiao** [comment]
The service has been relaunched.

**Comment by ZenonLiao** [comment]
Thx
