### ISSUE TITLE
CkipClassic Parser Client backend registration link

### ISSUE THREAD

**Issue by alalachin** [emfomy/ckipnlp#34]
I've seen some previous issues mentioning the link for CkipClassic Parser Client backend registration [http://parser.iis.sinica.edu.tw/v1/reg.exe](http://parser.iis.sinica.edu.tw/v1/reg.exe) was relaunched. But now I still cannot access the link. 
Please help, thanks!

**Comment by emfomy** [comment]
Registration link has been changed to http://parser.iis.sinica.edu.tw/v1/reg.php.
